### ISSUE TITLE
Extended list type support

### ISSUE THREAD

**Issue by Mytherin** [duckdb/pg_duckdb#101]
We should add support for more list types (e.g. floating point lists, etc).

**Comment by JelteF** [comment]
@Tishj I assume you didn't start on this yet

**Comment by mkaruza** [comment]
@JelteF we have used this ticket just as indicator and probably at this point doesn't make sense that it is still open. IMO, for any future data type support we should open different tickets.

**Comment by mkaruza** [comment]
Closing this issue. We should probably track new supported types by creating independent tickets.
