### ISSUE TITLE
security: GUC to block access to local filesystem

### ISSUE THREAD

**Issue by wuputah** [duckdb/pg_duckdb#105]
Discussed this a _long_ time ago... but currently we allow DuckDB to read from the local filesystem. This is a security risk; the CSV reader is particularly easy to use here since it will read just about any plain text file. 

This should instead be controllable via a GUC, default disabled, that can only be enabled by superuser.

**Comment by JohnHVancouver** [comment]
Another option would be to restrict it to certain directories?

**Comment by wuputah** [comment]
Yeah, could certainly do that as a further enhancement. My thought was you either are cool with accessing the filesystem (for testing, running on localhost, etc), or you're not (hosted / production environment).

**Comment by wearpants** [comment]
I have production uses for local data (not just dev/testing) & so would like this restricted to certain directories, instead of just on/off

`/etc/passwd` is a world-readable CSV file 😅

**Comment by wuputah** [comment]
ah, excellent!
