### ISSUE TITLE
can support greenplum6？

### ISSUE THREAD

**Issue by wonb168** [duckdb/pg_duckdb#131]

**Comment by JelteF** [comment]
Are there any specific issues you hit when compiling for Greenplum? If so, feel free to list them here and/or create a PR for those.

**Comment by wuputah** [comment]
Closing in favor of consolidating in #154... though I'll say I personally think Greenplum is a bit less likely since the source code seems to have gone closed source, so it's hard for us to test and officially support. Regardless, would be happy to see a PR to fix any issues.
