### ISSUE TITLE
Compilation error lz4.h: no such file or directory

### ISSUE THREAD

**Issue by isaiasanchez** [duckdb/pg_duckdb#146]
I'm getting this error during compilation process:
`...
-Wno-sign-compare  -I. -I./ -I/usr/include/postgresql/16/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/pgduckdb_detoast.o src/pgduckdb_detoast.cpp
src/pgduckdb_detoast.cpp:9:10: fatal error: lz4.h: No such file or directory
    9 | #include <lz4.h>
      |          ^~~~~~~
compilation terminated.
make: *** [<builtin>: src/pgduckdb_detoast.o] Error 1`

**Comment by wuputah** [comment]
Thanks for giving it a try.

You need to install `liblz4-dev` here (or similar, depending on your OS). Please try Googling for a more specific answer for your chosen OS. You should be able to figure out any missing dependencies pretty easily, for example:
https://askubuntu.com/questions/774806/fatal-error-lz4-h-no-such-file-or-directory-include-lz4-h
