### ISSUE TITLE
Installing pg_duckdb on Windows

### ISSUE THREAD

**Issue by enstarbob** [duckdb/pg_duckdb#175]
### Discussed in https://github.com/duckdb/pg_duckdb/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **enstarbob** September 11, 2024</sup>
Both PostgreSQL and DuckDB are installable on Windows, but the installation guidance for pg_duckdb doesn't mention Windows.

Is this just a documentation oversight and 'of course you can', or is there some extra limitation currently preventing it running on Windows?

Either way, it would be really useful if it could.</div>

**Comment by wuputah** [comment]
Sorry for the lack of response in the discussion, but this is covered under #154. I don't want an issue for every instance of "please support this platform, OS, etc." 😁

Windows support isn't an oversight in the README; it's not something we currently support, which means we don't test or build on Windows. If someone is very interested in WIndows support, we would welcome PRs to help with Windows compatibility.

Additionally, some features we're working on right now may not be supported on Windows, and we think that's OK. Ideally, anything that can't be supported on Windows would be disabled in that case.
