### ISSUE TITLE
Revert index scan functionality

### ISSUE THREAD

**Issue by JelteF** [duckdb/pg_duckdb#183]
@Tishj mentioned in #97 that we don't have tests for index scans. So I tried adding some basic tests for this. And as it turns out index scans are very much (and possibly completely) broken. This trivial example crashes the server for me:

```sql
CREATE TABLE test_table (id int primary key, name text);
SELECT * FROM test_table where id = 1;
```

**Comment by mkaruza** [comment]
Yes, imo all index functionality and code should be revisited again probably when i return back to finalize #71 feature.

**Comment by JelteF** [comment]
It was working in the past iirc, also at minimum it shouldn't crash the server, but throw a clear error.

**Comment by JelteF** [comment]
As discussed over chat. Our current Postgres index scan logic is incorrect. For 0.1.0 we've decided to revert the feature completely and only support sequential scans on postgres data from duckdb. It's definitely a feature we want, but we're not going to let it block version 0.1.0. We'll probably redesign it for version 0.2.0.
