### ISSUE TITLE
`enable_extension` function missing

### ISSUE THREAD

**Issue by rakesh-tmdc** [duckdb/pg_duckdb#209]
It is mentioned that to `Enable the DuckDB Iceberg extension using SELECT duckdb.enable_extension('iceberg') and read Iceberg files with iceberg_scan.` but when i do this i getting error that is - 

`
postgres=# SELECT duckdb.enable_extension('iceberg');
ERROR:  function duckdb.enable_extension(unknown) does not exist
LINE 1: SELECT duckdb.enable_extension('iceberg');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
`

This shows that the `enable_extension` function is not available.

**Comment by JelteF** [comment]
It's a mistake in the readme (I created a PR to fix that). You should use `duckdb.install_extension` instead.

**Comment by rakesh-tmdc** [comment]
Hey @JelteF Thanks for the update. I did try that below are the steps - 
 
`
postgres=# DROP EXTENSION IF EXISTS pg_duckdb; CREATE EXTENSION pg_duckdb; SET duckdb.execution TO true;SHOW duckdb.execution;


NOTICE:  extension "pg_duckdb" does not exist, skipping
DROP EXTENSION
WARNING:  To actually execute queries using DuckDB you need to run "SET duckdb.execution TO true;"
CREATE EXTENSION
SET
 duckdb.execution 
------------------
 on
(1 row)
`

`
postgres=# SELECT duckdb.install_extension('iceberg');

 install_extension 
-------------------
 t
(1 row)
`

`
postgres=# SELECT count(*) FROM iceberg_scan('s3a://****/sanity/iceberg/tablea') as (customerid TEXT);
WARNING:  (PGDuckDB/CreatePlan) Prepared query returned an error: 'Catalog Error: Table Function with name "iceberg_scan" is not in the catalog, but it exists in the iceberg extension.

Please try installing and loading the iceberg extension:
INSTALL iceberg;
LOAD iceberg;


WARNING:  (PGDuckDB/CreatePlan) Prepared query returned an error: 'Catalog Error: Table Function with name "iceberg_scan" is not in the catalog, but it exists in the iceberg extension.

Please try installing and loading the iceberg extension:
INSTALL iceberg;
LOAD iceberg;


ERROR:  Function `iceberg_scan(TEXT)` only works with Duckdb execution.
CONTEXT:  PL/pgSQL function iceberg_scan(text) line 3 at RAISE

`


this error shows that `iceberg_scan` function is also not available even when Duckdb execution is ON.

**Comment by JelteF** [comment]
Oh sorry, I somehow missed this response. That's indeed a bug. The workaround is to reconnect after calling `duckdb.install_extension()`. Then the `iceberg_scan` function should start working. I created #278 to track fixing that issue.
