### ISSUE TITLE
Decide on default DuckDB configuration that makes sense for use in postgres

### ISSUE THREAD

**Issue by JelteF** [duckdb/pg_duckdb#217]
- [ ] how many threads
- [ ] how much memory
- [ ] disabled_filesystems = 'LocalFilesystem' (fixes #105)
- [ ] more?

Related to but separate from #216

**Comment by JelteF** [comment]
Moving this to stability testing

**Comment by wuputah** [comment]
I believe this was the output of the discussion today:
* 4gb
* unbounded (default) threads
* max 1 thread per scan?
