### ISSUE TITLE
Support for table index

### ISSUE THREAD

**Issue by mkaruza** [duckdb/pg_duckdb#22]
If there exists index on table - research and explore possibility that they can be used for scan. 
Interesting would be to look into BRIN indexes that can be used as way to pre filter pages based on query filters.

**Comment by JelteF** [comment]
Is there still something actionable here for the 0.1.0 release?

**Comment by JelteF** [comment]
Closing this in favor of #243 (I didn't realise this issue was still open when I created that one). This issue was resolved, but we'll now revert its implementation for #183
