### ISSUE TITLE
Update README for 0.1.0 release

### ISSUE THREAD

**Issue by JelteF** [duckdb/pg_duckdb#287]
- [x] Explain setting up MotherDuck support
- [x] Mention 0.1.0 release
- [x] Docker install instructions
- [x] pgxman install instructions/link
- [x] PG15 support
- [x] shared_preload_libraries
- [x] temporary table support
- [x] Roadmap should link to milestones
- [x] Explain `ddb$` schema better: Prefixed with `ddb$` and a `$` inbetween database and schemaname, except if schema is `main`. You can only use the specific database. Postgres search_path = public not main
- [x] `USING duckdb` means its stored in duckdb/motherduck
- [x] List all functions that we support and/or link to the code where the functions are (e.g. no `read_json`)
- [x] List all GUCs
- [x] iceberg needs explicit install_extension
- [x] Needs restart after configuring motherduck support
- [x] Move Goals section to the end. Focus on existing features at the start
- [x] List officially supported DuckDB extensions
- [x] What else?

**Comment by Leo-XM-Zeng** [comment]
Add Postgres 15

![image](https://github.com/user-attachments/assets/0a0d7c71-14bf-4555-b9a2-6bb7d4a63a3f)

**Comment by Leo-XM-Zeng** [comment]
Pgxman seems to have support, do we need to describe it?

**Comment by Leo-XM-Zeng** [comment]
Need add pg_duckdb to shared_preload_libraries

**Comment by Leo-XM-Zeng** [comment]
Do we need to specify which data types are supported by the current version?

**Comment by mehd-io** [comment]
I believe there's a typo [here](https://github.com/duckdb/pg_duckdb/blob/main/README.md?plain=1#L138) , extra $

**Comment by JelteF** [comment]
> I believe there's a typo [here](https://github.com/duckdb/pg_duckdb/blob/main/README.md?plain=1&rgh-link-date=2024-10-18T07%3A53%3A16Z#L138) , extra $

For me that query works. What do you think it should be?

**Comment by mehd-io** [comment]
@JelteF In the current readme we talk about AWS S3, Cloudflare R2, or Google GCS and sometimes `S3, GCP and Azure`.
* Do we support all of them ? There aren't any interface to do secrets wise that we had to do ? If not, do we support also HuggingFace secrets and pulling dataset from there ?
* Let's be consistent with the naming :  `AWS S3, GCP Cloud Storage and Azure Blob Storage`

**Comment by mehd-io** [comment]
Regarding DuckDB extensions - do we support them all ? I think we need to adapt the language there, otherwise people will think that everything just work.

**Comment by wuputah** [comment]
* [ ] document all (functions and) settings
