### ISSUE TITLE
DuckDB secrets table should have a PK and/or name column

### ISSUE THREAD

**Issue by mehd-io** [duckdb/pg_duckdb#289]
At the moment, there's no PK or name alias (as there's in the DuckDB secrets manager) on `duckdb.secrets`, making it hard to delete specific secrets.

This is the error I got when inserting twice a secrets :
```
 (PGDuckDB/DuckDBQuery) Invalid Input Error: Initialization function "httpfs_init" from file "/var/lib/postgresql/17/data/duckdb_extensions/v1.1.1/linux_amd64/httpfs.duckdb_extension" threw an exception: "Attempted to register an already registered secret type: 's3'"
 ```

**Comment by Y--** [comment]
++ also, it should be an error to insert the same secret twice, otherwise DuckDB will throw an error on each successive query until the user removes the duplicate.
