### ISSUE TITLE
Set dockerhub description

### ISSUE THREAD

**Issue by wuputah** [duckdb/pg_duckdb#333]
This page is empty: https://hub.docker.com/r/pgduckdb/pgduckdb. We should fix that, somehow. A Docker-specific readme would be ideal, but the current readme would be fine.

We can set this via GHA per the docs here: https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/

The only caveat is that Dockerhub doc claims you can use the token, despite the action docs not mentioning it: https://github.com/peter-evans/dockerhub-description

All else fails, we can set it manually once.

**Comment by Y--** [comment]
Updated, let me know if I've missed anything.
