### ISSUE TITLE
Add `postgres_mode` to DuckDB that makes it simulate Postgres in a better capacity

### ISSUE THREAD

**Issue by Mytherin** [duckdb/pg_duckdb#36]
This mode is a (very long tail) mode that improves compatibility between DuckDB's SQL dialect and Postgres' SQL dialect.

e.g.:

* `SELECT COUNT(*) FROM tbl` returns a column named `count`, instead of `count_star()`

**Comment by JelteF** [comment]
I think all the things in this issue have now been solved/worked around some other way. We might still need a "postgres_mode" feature in duckdb for other reasons, but let's create separate issues for these things when we find them.
