### ISSUE TITLE
Prepared statments, and stored procedures are not working properly.

### ISSUE THREAD

**Issue by zhousun** [duckdb/pg_duckdb#396]
### What happens?

When prepare have parameters, duckdb will fail to bind the types, and latter rely on execution to rebind them with actual values.

But pg_duckdb is using it in an incorrect way,  assuming Prepare will fully resolve all the types without providing actual values.

### To Reproduce
```
postgres=# prepare test(int) as select * from a where a>$1+1; 
PREPARE    
postgres=# execute test(1);
WARNING:  (PGDuckDB/GetPostgresDuckDBType) Could not convert DuckDB type: UNKNOWN to Postgres type
WARNING:  (PGDuckDB/CreatePlan) Cache lookup failed for type 0
 a 
---
(0 rows)
```

### OS:

MacOs

### pg_duckdb Version:

0.1.0

### Postgres Version:

16

### Full Name:

Zhou

### Affiliation:

Mooncake Labs

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

No - Other reason (please specify in the issue body)

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by JelteF** [comment]
Closing this in favor of #480 as it provides more information on this issue.
