### ISSUE TITLE
Any stored procedure is not working 

### ISSUE THREAD

**Issue by zhousun** [duckdb/pg_duckdb#411]
### What happens?

Stored procedure will run each query with more parameters, thus will always hit assert in duckdb.

### To Reproduce

```
postgres=# create table t(a int);
CREATE TABLE
postgres=# SET duckdb.force_execution TO true;
SET
postgres=# CREATE OR REPLACE PROCEDURE t(b INT)
LANGUAGE plpgsql
AS $$
BEGIN
    select * from t where a=b;
END;
$$;
CREATE PROCEDURE
postgres=# call t(1);
ERROR:  (PGDuckDB/Duckdb_ExecCustomScan) Invalid Input Error: Parameter argument/count mismatch, identifiers of the excess parameters: 2
CONTEXT:  SQL statement "select * from t where a=b"
PL/pgSQL function t(integer) line 3 at SQL statement

```

### OS:

MacOs

### pg_duckdb Version:

0.1.0

### Postgres Version:

16

### Full Name:

Zhou

### Affiliation:

Mooncake Labs

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by zhousun** [comment]
I would suggest following fix:
simply populate prepared->named_param_map with all parameters

**Comment by dpxcc** [comment]
@JelteF Do we have any plan on this?
Being able to run analytics query using pg_duckdb inside stored procedure seems very useful

**Comment by JelteF** [comment]
Agreed, that this is an issue that should be fixed. Feel free to create a PR for it.
