### ISSUE TITLE
COPY pg_view TO s3 fails with missing scalar function

### ISSUE THREAD

**Issue by laogao** [duckdb/pg_duckdb#437]
### What happens?

When I try to `COPY (SELECT * FROM some_pg_view_built_with_pg_functions) TO 's3://...'`, it fails with the following error:

```
ERROR:  (PGDuckDB/DuckDBQuery) Catalog Error: Scalar Function with name to_char does not exist!
Did you mean "to_hours"?
```

Copy to local path e.g. `COPY (SELECT * FROM some_pg_view_built_with_pg_functions) TO '/tmp/some.csv'` works, though.

### To Reproduce

```sql
CREATE EXTENSION IF NOT EXISTS pg_duckdb;
CREATE VIEW pg_view AS (SELECT to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'::text) AS ts);
COPY (SELECT * FROM pg_view) TO '/tmp/pg_view.csv';
COPY (SELECT * FROM pg_view) TO 's3://media/pg_view.csv';
```

### OS:

Linux

### pg_duckdb Version (if built from source use commit hash):

0.1.0

### Postgres Version (if built from source use commit hash):

17.0

### Full Name:

Sean Gao

### Affiliation:

Palan DataRx

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by JelteF** [comment]
Currently you can only use functions in queries that also exist in DuckDB, for queries that require duckdb execution. This is a known issue. It also does not depend on using a view. You get the same error when simply putting your query in the `COPY` statement directly.
```
> COPY (SELECT to_char(NOW(), 'YYYY-MM-DD HH24:MI:SS'::text)) TO 's3://media/pg_view.csv';
ERROR:  XX000: (PGDuckDB/DuckdbUtilityHook) Catalog Error: Scalar Function with name to_char does not exist!
Did you mean "to_hours"?
```

**Comment by laogao** [comment]
Okay. So, if I understand this correctly, what happens is that views are in effect "inlined" as part of the query rather than treated as a regular table to select from? This is somewhat unintuitive as I'm not calling the functions directly. It's all "behind the scenes". Sometimes it's necessary (or helpful) to have views that are managed by another team.

From a designing perspective, what are the downsides if we choose to handle views the same as tables in `COPY (SELECT ...) TO`? Or, are there any fundamental design choices that make this unattainable?

**Comment by JelteF** [comment]
> So, if I understand this correctly, what happens is that views are in effect "inlined" as part of the query rather than treated as a regular table to select from? This is somewhat unintuitive as I'm not calling the functions directly. 

Correct, that's also how views work when querying them with plain Postgres. The main reason that's the case is because then you can update the data in the underlying tables and the result from the view is automatically up to date. If you want to take a snapshot in time and store that "as if it was a table" you can use "materialized views".

**Comment by laogao** [comment]
> > So, if I understand this correctly, what happens is that views are in effect "inlined" as part of the query rather than treated as a regular table to select from? This is somewhat unintuitive as I'm not calling the functions directly.
> 
> Correct, that's also how views work when querying them with plain Postgres. The main reason that's the case is because then you can update the data in the underlying tables and the result from the view is automatically up to date. If you want to take a snapshot in time and store that "as if it was a table" you can use "materialized views".

Got it. If that is the case, where should I look to find the full list of supported functions (the ones `pg_duckdb` replicates)? Or, is it the same list as plain DuckDB supports? If we are talking about pg and duckdb functions with corresponding names (which means `pg_duckdb` would pick the one with the same name), how does one make sure they have equivalent behavior? It would be nice to have `COPY TO` queries which simultaneously support both local and s3 output targets.

**Comment by JelteF** [comment]
So currently there's no guarantee that these functions have equivalent behavior. Basically we hand over the full query to duckdb, and if the functions you tried to call don't exist there, then the query will fail.

**Comment by laogao** [comment]
I see. So the current `pg_duckdb` behavior is by design. I'm closing this bug for now. Please re-consider this particular use case in future versions. Thanks.
