### ISSUE TITLE
INSERT errors when using default values

### ISSUE THREAD

**Issue by dpxcc** [duckdb/pg_duckdb#445]
### What happens?

INSERT errors when using default values because `pgduckdb_get_querydef()` results in invalid SQL query

### To Reproduce

```sql
CREATE TEMP TABLE t (a int DEFAULT 3, b int) USING duckdb;
INSERT INTO t (b) VALUES (123), (456);
```
throws error
```sql
2024-11-19 00:15:50.950 UTC [3577] ERROR:  (PGDuckDB/CreatePlan) Prepared query returned an error: 'Binder Error: Column name/value mismatch for insert on t: expected 2 columns but 1 values were supplied
```
because `pgduckdb_get_querydef()` returns
```
INSERT INTO pg_temp.main.t (a, b) VALUES (123), (456)
```

### OS:

Linux

### pg_duckdb Version (if built from source use commit hash):

0.1.0

### Postgres Version (if built from source use commit hash):

17.0

### Full Name:

Cheng Chen

### Affiliation:

Mooncake Labs

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by JelteF** [comment]
Okay, a bit more info. The function that adds these `Const` nodes is `rewriteTargetListIU`, and there's a hook we can use to get the query tree before that function is called: `post_parse_analyze_hook`. 

Using the `post_parse_analyze_hook` to store the original query tree seems like it could be a bit expensive though. At the very least we'd have to call `NeedsDuckdbExecution` there.

Looking at `rewriteTargetListIU` it doesn't seem to do any other things that would impact the query returned by `pgduckdb_get_querydef` in a meaningful way (i.e. where it breaks the query like reported here). So I think the best approach is to go for option 2, and make our vendored ruleutils ignore target entries of type `Const`.
