### ISSUE TITLE
New MotherDuck databases are not detected without PG restart

### ISSUE THREAD

**Issue by jtigani** [duckdb/pg_duckdb#450]
### What happens?

If you want to create a table in a motherduck database that doesn't have any tables, you get the error
`ERROR:  schema "ddb$foo" does not exist`

This persists even if you create tables in that database. It starts working once you restart postgres.

### To Reproduce

in motherduck ui,
`CREATE DATABASE foo`

start postgres/pgduckdb

```
$ psql
postgres=# CREATE TABLE ddb$foo.orders(id bigint, item text, price NUMERIC(10, 2)) USING duckdb;
ERROR:  schema "ddb$pgclick" does not exist
```
If you create a table in the motherduck UI you'll continue to get this error. However, if you restart postgres after creating a table, it works.

### OS:

Ubuntu

### pg_duckdb Version (if built from source use commit hash):

pgduckdb/pgduckdb:16-main

### Postgres Version (if built from source use commit hash):

16

### Full Name:

Jordan Tigani

### Affiliation:

MotherDuck

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a nightly build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by JelteF** [comment]
This is a known issue that @ywelsch is working on. New motherduck databases are only synced with new clients, not with already connected clients (e.g. pg_duckdb, but also the duckdb cli).

I double checked that an empty database is also synced after PG restart. There is no need for tables to be in it.
