### ISSUE TITLE
DuckDB crashes when doing query on schema named "main" in Postgres. 

### ISSUE THREAD

**Issue by Bigknoob** [duckdb/pg_duckdb#458]
### What happens?

When using DuckDB v1.1.3 with the Postgres extension (https://duckdb.org/docs/extensions/postgres.html), DuckDB crashes when querying a schema named "main."

I can successfully attach several databases and use the SHOW ALL TABLES; command to view all tables, including those under the schema named "main." However, attempting to execute a query such as SELECT * FROM alias.main.streets; causes DuckDB to crash.
Seems like a schema name conflict? 

### To Reproduce

```
INSTALL postgres;
LOAD postgres;

ATTACH 'dbname=db_info user=beaver password=123 host=beavertown.postgresql-dev.com' as postgres_db_info (TYPE POSTGRES);
ATTACH 'dbname=db_main user=beaver password=123 host=beavertown.postgresql-dev.com' as postgres_db_main (TYPE POSTGRES);

SHOW ALL TABLES;
-- this shows all schemas and tables for both databases. 

SELECT * FROM postgres_db_info.info.test; 
-- this query works

SELECT * FROM postgres_db_main.main.test;
--duckdb crashes. 

```

### OS:

Windows

### pg_duckdb Version (if built from source use commit hash):

0.1.0

### Postgres Version (if built from source use commit hash):

16.3

### Full Name:

William Vagle

### Affiliation:

Fraktal

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have not tested with any build

### Did you include all relevant data sets for reproducing the issue?

No - I cannot share the data sets because they are confidential

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by wuputah** [comment]
Hi! You're looking for the `postgres_scanner` DuckDB extension, not `pg_duckdb`, which is a Postgres extension. Please re-file your issue at https://github.com/duckdb/postgres_scanner.
