### ISSUE TITLE
Partitioned writes failing due to query rewrite changing PARTITION_BY field format from '(year,month,day)' to 'year.month.day'

### ISSUE THREAD

**Issue by sysadminmike** [duckdb/pg_duckdb#462]
### What happens?

The following query fails:

`COPY (select year, month, day, counter from myschema.mytable) TO 's3://bucket/testhive.parquet' ( FORMAT 'parquet', PARTITION_BY (year, month, day) )`

From DEBUG logs the incomming and rewritten query:

```
2024-11-29 12:13:39.793 UTC [34593] postgres@duck DEBUG:  parse <unnamed>:
        COPY (select year, month, day, counter from myschema.mytable)
              TO 's3://bucket/testhive.parquet' ( FORMAT 'parquet', PARTITION_BY (year, month, day) )
	  
2024-11-29 12:13:39.793 UTC [34593] postgres@duck DEBUG:  (PGDuckDB/CreateRelationCopyString) Rewritten query: 'COPY (SELECT year, month, day, counter FROM pgduckdb.myschema.mytable) TO 's3://bucket/testhive.parquet' (format 'parquet', partition_by year.month.day);'
2024-11-29 12:13:39.793 UTC [34593] postgres@duck ERROR:  (PGDuckDB/DuckdbUtilityHook) Parser Error: syntax error at or near "."
        LINE 1: ...t' (format 'parquet', partition_by year.month.day);
                                                          ^

```

### To Reproduce

`COPY (select year, month, day, counter from myschema.mytable) TO 's3://bucket/testhive.parquet' ( FORMAT 'parquet', PARTITION_BY (year, month, day) )`

### OS:

Linux

### pg_duckdb Version (if built from source use commit hash):

na

### Postgres Version (if built from source use commit hash):

17

### Full Name:

Michael Wolman

### Affiliation:

NA

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by JelteF** [comment]
Thanks for the report that's definitely a bug. I don't think it will be difficult to fix once we make some of the other copy improvements that we want to do.

**Comment by wuputah** [comment]
I'm not sure whether copy partitioning was actually supposed to work or not yet 😅  but would love to see this fully supported.

**Comment by JelteF** [comment]
For who-ever picks this up. I'm pretty sure this is the incorrect bit of code: https://github.com/duckdb/pg_duckdb/blob/0b400af176f9e3e4fa54cf55fbfb22e93ae55543/src/utility/copy.cpp#L149

I think the partition by clause is interpreted as a name list, and we're then serializing it to an identifier representation, which is clearly wrong in this case. Afaict this behaviour is incorrect for all COPY options. I expect that this same thing also breaks the following Postgres options (not sure if those are all supported by duckdb).

```
    FORCE_QUOTE { ( column_name [, ...] ) | * }
    FORCE_NOT_NULL { ( column_name [, ...] ) | * }
    FORCE_NULL { ( column_name [, ...] ) | * }
```
