### ISSUE TITLE
Unable to support huge number

### ISSUE THREAD

**Issue by dentiny** [duckdb/pg_duckdb#467]
### What happens?

`pg_duckdb` seems to fail on huge value insertion, in detail, prepared statement generation fails.

### To Reproduce

```
postgres (pid: 599) =# CREATE TEMP TABLE t (large_number NUMERIC) USING duckdb;
CREATE TABLE
postgres (pid: 599) =# INSERT INTO t (large_number) VALUES (200141183460469231731687303715884105727);
WARNING:  INSERT INTO pg_temp.main.t (large_number) VALUES ('200141183460469231731687303715884105727'::numeric)
ERROR:  (PGDuckDB/CreatePlan) Prepared query returned an error: 'Conversion Error: Could not convert string "200141183460469231731687303715884105727" to DECIMAL(18,3)
LINE 1: ...00141183460469231731687303715884105727'::numeric)
```

### OS:

Linux

### pg_duckdb Version (if built from source use commit hash):

535b092b7c7448e8f349a15243d76c63a6a73462

### Postgres Version (if built from source use commit hash):

17

### Hardware:

aarch64, 64-bit

### Full Name:

Hao

### Affiliation:

N/A

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by dentiny** [comment]
Some initial investigation:
`query_string` produced b https://github.com/duckdb/pg_duckdb/blob/c3e80d8c27cc681380cf87b0e1f1ea95da87dcad/src/pgduckdb_planner.cpp#L35 default uses `numeric(18, 3)` as default type, which fails to parse.

**Comment by JelteF** [comment]
NUMERIC in DuckDB works quite different than NUMERIC in Postgres. With [DuckDB the default numeric size is 18 (width), 3 (scale)](https://duckdb.org/docs/sql/data_types/numeric.html#fixed-point-decimals). You're trying to insert a larger number than that into the table. If you need larger numbers you can provide a different width and scale to use something different than the default.

DuckDB doesn't support numerics nearly as large as postgres though.

**Comment by dentiny** [comment]
Understand, thanks you for the confirmation and explanation!
