### ISSUE TITLE
An error was reported when pg_duckdb was installed on postgreSQL14.13

### ISSUE THREAD

**Issue by Serendipityxx** [duckdb/pg_duckdb#505]
### What happens?

When installing a compilation in postgreSQL14.13, there are some compilation error and undefine symbol error...

### To Reproduce

My steps：
1、`git clone https://github.com/duckdb/pg_duckdb`
2、`cd pg_duckdb && make -j8`
3、`sudo make install`

```
make: pg_config: No such file or directory
make: pg_config: No such file or directory
make: pg_config: No such file or directory
make: pg_config: No such file or directory
OVERRIDE_GIT_DESCRIBE=v1.1.3 \
GEN=ninja \
CMAKE_VARS="-DBUILD_SHELL=0 -DBUILD_PYTHON=0 -DBUILD_UNITTESTS=0" \
DISABLE_SANITIZER=1 \
DISABLE_ASSERTIONS=0 \
EXTENSION_CONFIGS="../pg_duckdb_extensions.cmake" \
make -C third_party/duckdb \
release
make[1]: Entering directory '/home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb'
mkdir -p ./build/release && \
cd build/release && \
cmake -G "Ninja" -DFORCE_COLORED_OUTPUT=1     -DENABLE_SANITIZER=FALSE -DENABLE_UBSAN=0  -DBUILD_SHELL=0 -DBUILD_PYTHON=0 -DBUILD_UNITTESTS=0 -DENABLE_EXTENSION_AUTOLOADING= -DENABLE_EXTENSION_AUTOINSTALL= -DDUCKDB_EXTENSION_CONFIGS="../pg_duckdb_extensions.cmake" -DLOCAL_EXTENSION_REPO=""  -DOVERRIDE_GIT_DESCRIBE="v1.1.3"  -DCMAKE_BUILD_TYPE=Release ../.. && \
cmake --build . --config Release
-- git hash 19864453f7, version v1.1.3, extension folder v1.1.3
-- Extensions will be deployed to: /home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb/build/release/repository
-- Load extension 'json' from '/home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb/extensions' @ v1.1.3
-- Load extension 'cached_httpfs' from '/home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb/../cached_httpfs' @ v0.2.0
-- Load extension 'parquet' from '/home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb/extensions' @ v1.1.3
-- Load extension 'jemalloc' from '/home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb/extensions' @ v1.1.3
CMake Warning at CMakeLists.txt:1240 (message):
  Extension 'cached_httpfs' has a vcpkg.json, but build was not run with
  VCPKG.  If build fails, check out VCPKG build instructions in
  'duckdb/extension/README.md' or try manually installing the dependencies in
  /home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb/../cached_httpfsvcpkg.json


-- Extensions linked into DuckDB: [json, cached_httpfs, parquet, jemalloc]
-- Configuring done (2.9s)
-- Generating done (0.6s)
-- Build files have been written to: /home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb/build/release
[6/6] Linking CXX shared library src/libduckdb.so
make[1]: Leaving directory '/home/xiangxiao/postgressql/code_pg/pg1413/postgresql/contrib/pg_duckdb/third_party/duckdb'
m 755 third_party/duckdb/build/release/src/libduckdb 
make: m: No such file or directory
make: [Makefile:101: install-duckdb] Error 127 (ignored)
```

But when I do not do `sudo make install`, but do `make install`, I also have problems as shown below:

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -fPIC -shared -o pg_duckdb.so  src/pgduckdb_background_worker.o src/pgduckdb.o src/pgduckdb_ddl.o src/pgduckdb_detoast.o src/pgduckdb_duckdb.o src/pgduckdb_filter.o src/pgduckdb_hooks.o src/pgduckdb_metadata_cache.o src/pgduckdb_node.o src/pgduckdb_options.o src/pgduckdb_planner.o src/pgduckdb_ruleutils.o src/pgduckdb_table_am.o src/pgduckdb_types.o src/pgduckdb_utils.o src/pgduckdb_xact.o src/catalog/pgduckdb_catalog.o src/catalog/pgduckdb_schema.o src/catalog/pgduckdb_storage.o src/catalog/pgduckdb_table.o src/catalog/pgduckdb_transaction.o src/catalog/pgduckdb_transaction_manager.o src/pg/error_data.o src/pg/relations.o src/pg/transactions.o src/scan/heap_reader.o src/scan/postgres_scan.o src/scan/postgres_seq_scan.o src/utility/copy.o src/vendor/pg_explain.o  src/vendor/pg_ruleutils_14.o src/vendor/pg_ruleutils_15.o src/vendor/pg_ruleutils_16.o src/vendor/pg_ruleutils_17.o -L/home/xiangxiao/postgressql/install_pg/lib    -Wl,--as-needed -Wl,-rpath,'/home/xiangxiao/postgressql/install_pg/lib',--enable-new-dtags  -Wl,-rpath,/home/xiangxiao/postgressql/install_pg/lib/ -lpq -Lthird_party/duckdb/build/release/src -L/home/xiangxiao/postgressql/install_pg/lib -lduckdb -lstdc++ -llz4 
/usr/bin/mkdir -p '/home/xiangxiao/postgressql/install_pg/lib'
/usr/bin/mkdir -p '/home/xiangxiao/postgressql/install_pg/share/extension'
/usr/bin/mkdir -p '/home/xiangxiao/postgressql/install_pg/share/extension'
/usr/bin/install -c -m 755  pg_duckdb.so '/home/xiangxiao/postgressql/install_pg/lib/pg_duckdb.so'
/usr/bin/install -c -m 755 third_party/duckdb/build/release/src/libduckdb.so /home/xiangxiao/postgressql/install_pg/lib
/usr/bin/install -c -m 644 .//pg_duckdb.control '/home/xiangxiao/postgressql/install_pg/share/extension/'
/usr/bin/install -c -m 644 .//pg_duckdb.control .//sql/pg_duckdb--0.1.0--0.2.0.sql .//sql/pg_duckdb--0.1.0.sql  '/home/xiangxiao/postgressql/install_pg/share/extension/'
```
The above path is also somewhat problematic.

And when I use the `ldd -r` command, I can see this problem:

![image](https://github.com/user-attachments/assets/0af12315-ebdb-4c43-a2de-54e77123704f)

### OS:

Fedora/Ubuntu22.04 x86_64

### pg_duckdb Version (if built from source use commit hash):

tag: v0.2.0

### Postgres Version (if built from source use commit hash):

tag: v14.13

### Full Name:

XiangXiao

### Affiliation:

2311711863@qq.com

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by Y--** [comment]
Hi! Thanks for the report.
The latest [CI run](https://github.com/duckdb/pg_duckdb/actions/runs/12352286025/job/34468997740) seem to indicate that the build is working with Postgres' `REL_14_STABLE` branch.

Could you provide a Dockerfile that reproduces the problem? Thanks!

**Comment by Serendipityxx** [comment]
I use the source code is compiled and installed, my environment Settings are as follows:
![image](https://github.com/user-attachments/assets/fcaf089d-fc9d-4fab-b472-17081706f375)
I think the pg_config path set in the Makefile.global file is not very clear, whether I need to display the specified pg_config path
![image](https://github.com/user-attachments/assets/a4417d2e-f88c-4df8-b350-accb671807ba)

**Comment by Y--** [comment]
I've tried the following Dockerfile, and it worked successfully for me:
```
FROM ubuntu:22.04

RUN apt-get update -qq && \
    apt-get install -y \
    build-essential libreadline-dev zlib1g-dev flex bison libxml2-dev libxslt-dev \
    libssl-dev libxml2-utils xsltproc pkg-config libc++-dev libc++abi-dev libglib2.0-dev \
    cmake libstdc++-12-dev liblz4-dev ccache ninja-build git && \
    rm -rf /var/lib/apt/lists/*

RUN git clone --depth 1 --branch REL_14_13 git://git.postgresql.org/git/postgresql.git

RUN git clone --depth 1 https://github.com/duckdb/pg_duckdb.git

WORKDIR /postgresql

RUN mkdir -p /tmp/pg && \
    ./configure --prefix=/tmp/pg \
        --enable-debug \
        --enable-cassert \
        --enable-depend \
        --with-icu \
        --with-openssl \
        --with-libxml \
        --with-libxslt

RUN make install -j$(nproc)

WORKDIR /pg_duckdb

RUN export PATH=/tmp/pg/bin:$PATH \
    && make install -j$(nproc)
```

Could you check on your end the differences with this? Thanks!

**Comment by Serendipityxx** [comment]
My actions are pretty much the same as above. In the `Makefile.global` file, I didn't get a `make` error after manually specifying the `pg_config` path, but there is a difference between `make installcheck` and `make check` when performing regression tests.
![image](https://github.com/user-attachments/assets/5f50e550-427c-4a37-b1a9-f1bcf3c10129)
![image](https://github.com/user-attachments/assets/b4c41dd0-eb96-4a37-9e9b-91de370bcdc3)

**Comment by Serendipityxx** [comment]
My actions are pretty much the same as above. In the Makefile.global file, I didn't get a make error after manually specifying the pg_config path, but there is a difference between make installcheck and make check when performing regression tests.
![image](https://github.com/user-attachments/assets/e2171ef3-f7f0-4368-a52a-4b9aece04b60)

![image](https://github.com/user-attachments/assets/75e68af0-b020-4ff4-9346-d6fa8788a07a)

**Comment by Leo-XM-Zeng** [comment]
Want to take a look at your config.log
```plpgsql
cd postgresql_code
more config.log
```

**Comment by Y--** [comment]
I haven't run the full suite yet, let me check that.

**Comment by Serendipityxx** [comment]
I can see why. The problem came from the fact that I didn't introduce other dependencies when compiling. I introduced missing dependencies and regress passed. But the new problem I encountered was that I noticed that after the regression test, a pytest command was executed, but when executed, an error was reported, as follows:
![image](https://github.com/user-attachments/assets/6e2217fb-6174-4712-b551-c11ca5808c9c)

**Comment by Y--** [comment]
Just making sure- did you install the Python dependencies as specified [here](https://github.com/duckdb/pg_duckdb/blob/main/CONTRIBUTING.md#python-dependencies)?

**Comment by Y--** [comment]
I've put up a [PR](https://github.com/duckdb/pg_duckdb/pull/506) to address the test issue reported above:
```
+ERROR:  collation "de-x-icu" for encoding "SQL_ASCII" does not exist
+LINE 1: CREATE TEMP TABLE t(a text COLLATE "de-x-icu");
```

**Comment by Y--** [comment]
When this PR lands, all test should be green, assuming you configure PG build with the following flags:
```
--with-icu --with-openssl --with-libxml --with-lz4 --with-libxslt
```

**Comment by Serendipityxx** [comment]
The current situation is that the regression of the pgregress can pass, but when using pytest, there will be an import error message, which is as follows:
![image](https://github.com/user-attachments/assets/78ca41a7-3bb3-4db5-8e7a-130190c7925e)

**Comment by Y--** [comment]
> The current situation is that the regression of the pgregress can pass, but when using pytest, there will be an import error message, which is as follows: ![image](https://private-user-images.githubusercontent.com/103412215/397716328-78ca41a7-3bb3-4db5-8e7a-130190c7925e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2OTM2MjMsIm5iZiI6MTczNDY5MzMyMywicGF0aCI6Ii8xMDM0MTIyMTUvMzk3NzE2MzI4LTc4Y2E0MWE3LTNiYjMtNGRiNS04ZTdhLTEzMDE5MGM3OTI1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMFQxMTE1MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGZkNzk1NDkwZWZlMmZkYjhmMmNhZTU5MjEwYWIzNWQxMjU1MmNhOTY5MDhkOWJiMWYxOTNkZGU4YzI0YjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EIRsKthafZ0qoL-4TaGAl_zksLXs5PMNxa9JUDxDOV0)

Try to set `LD_LIBRARY_PATH` like this?
```
export LD_LIBRARY_PATH=$(pg_config --libdir):$LD_LIBRARY_PATH
```

**Comment by Serendipityxx** [comment]
After I found the import error, I added LD_LIBRARY_PATH environment variable. The current situation is that after make check is executed, there will be the following message, is this normal?
![image](https://github.com/user-attachments/assets/fe426634-86c9-4e1d-940c-e0d456874bdf)

**Comment by Y--** [comment]
Yes, I think this is normal, PG expects you to run 
```bash
$ make installcheck
```
and you can run
```bash
$ make pycheck
```
to run the python tests.

Maybe @JelteF can give some context on this?

**Comment by Serendipityxx** [comment]
After I run make installcheck, the result is that the regression tests all pass.However, I modified the code according to the commit you gave, but the above problem still occurred, I guess this should be a normal situation, and then I will read the code in depth, thank you very much!
![image](https://github.com/user-attachments/assets/ac2ea8ab-de4b-4740-9cea-d2af8bf5aecd)

Finally, thanks to the online guidance of two Programming gurus, I was able to successfully install the entire plugin on postgreSQL.Good luck to you,and this star for you!
![image](https://github.com/user-attachments/assets/5583a458-ca2e-4cd3-9666-4421242f1cea)

**Comment by Y--** [comment]
Thanks for confirming that it works for you! Closing this one, feel free to open a new issue if you spot something else.

**Comment by Serendipityxx** [comment]
I'm sorry to bother you again, but I have a new problem. When I execute the make pycheck command, I get the following error message:
![image](https://github.com/user-attachments/assets/66dc19e1-0e28-473a-9fb6-9b3a7ce63bba)
I have executed the pip install -r dev_requirements.txt command and set the PATH and LD_LIBRARY_PATH environment variables.
Since I compiled postgreSQL1413 from source code, normally there is libpq.so and can import successfully, but why can't import, do I need to install this psycopg3 dependency?

**Comment by Leo-XM-Zeng** [comment]
> I'm sorry to bother you again, but I have a new problem. When I execute the make pycheck command, I get the following error message: ![image](https://private-user-images.githubusercontent.com/103412215/398165080-66dc19e1-0e28-473a-9fb6-9b3a7ce63bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjY5MjksIm5iZiI6MTczNDk2NjYyOSwicGF0aCI6Ii8xMDM0MTIyMTUvMzk4MTY1MDgwLTY2ZGMxOWUxLTBlMjgtNDczYS05ZmI2LTliM2E3Y2U2M2JiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxNTEwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDkxYTAxY2Y2N2E5YWMyNzVhNmI0NmY2OWVkNjdkYjA2NDI1OTMxOWUwNDYwYTgzNzJlMjFkMDE5ZWE1N2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bY3yoNHlUeScjeKTcT0q7h4xv7GonYCxaZ7-LnwS0ME) I have executed the pip install -r dev_requirements.txt command and set the PATH and LD_LIBRARY_PATH environment variables. Since I compiled postgreSQL1413 from source code, normally there is libpq.so and can import successfully, but why can't import, do I need to install this psycopg3 dependency?

Have you ever installed a version lower than 14 in your environment? If I remember correctly, pg_hmac_free was introduced in version 14.

**Comment by Serendipityxx** [comment]
> > I'm sorry to bother you again, but I have a new problem. When I execute the make pycheck command, I get the following error message: ![image](https://private-user-images.githubusercontent.com/103412215/398165080-66dc19e1-0e28-473a-9fb6-9b3a7ce63bba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NjY5MjksIm5iZiI6MTczNDk2NjYyOSwicGF0aCI6Ii8xMDM0MTIyMTUvMzk4MTY1MDgwLTY2ZGMxOWUxLTBlMjgtNDczYS05ZmI2LTliM2E3Y2U2M2JiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxNTEwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NDkxYTAxY2Y2N2E5YWMyNzVhNmI0NmY2OWVkNjdkYjA2NDI1OTMxOWUwNDYwYTgzNzJlMjFkMDE5ZWE1N2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bY3yoNHlUeScjeKTcT0q7h4xv7GonYCxaZ7-LnwS0ME) I have executed the pip install -r dev_requirements.txt command and set the PATH and LD_LIBRARY_PATH environment variables. Since I compiled postgreSQL1413 from source code, normally there is libpq.so and can import successfully, but why can't import, do I need to install this psycopg3 dependency?
> 
> Have you ever installed a version lower than 14 in your environment? If I remember correctly, pg_hmac_free was introduced in version 14.

ok，I have solved this problem. This problem is because of the port binding part.
