### ISSUE TITLE
Azure support (extension, secret, az://, abfss://)

### ISSUE THREAD

**Issue by wuputah** [duckdb/pg_duckdb#52]
https://duckdb.org/docs/extensions/azure

* Azure is its own extension, so this needs to be added
* Authentication is a bit bespoke - https://duckdb.org/docs/extensions/azure#authentication
* There is both `az://` and `abfss://` protocols

**Comment by tomtom215** [comment]
It would be great to also have pg_duckdb as an official extension offered for Azure managed postgres https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions

**Comment by pantonis** [comment]
I don't understand why initial release does not support azure and supports cloudflare.

**Comment by JelteF** [comment]
@pantonis cloudflare implements the S3 API. So support is basically free once we implemented S3 support. Azure support requires a little bit more work, due to the API differences.

**Comment by JelteF** [comment]
No promises, but I think it would be surprising if this feature does not make the cut for 0.2.0. Feel free to contribute a PR though.

**Comment by pantonis** [comment]
I would If I was a C++ dev. I might cause more problems than solve :)
However I can easily test it as soon as you have a version.

**Comment by JelteF** [comment]
Fixed by #478 (which will be released in the 0.2.0 release that's planned for next week). If certain behavior is not working please report that as a new issue.

**Comment by CaselIT** [comment]
Maybe a new issue could be opened that tracks the availability of this extension in the azure extension catalog listed here https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions

Note that I'm not sure how one gets added there, it may be entirely in azure hands
